feature: different templates for context/indexes

diff --git a/build_pages b/build_pages
--- a/build_pages
+++ b/build_pages
@@ -32,7 +32,6 @@ if [ "$1" == "force" ] ; then
   rm $DB/last_gen
 fi
 
-
 # If we know about the last generation, find updated content; if not (or if we
 # force it), find all content. All content to queue.
 if [ -e $DB/last_gen ] ; then
@@ -56,6 +55,7 @@ for ITEM in $(cat $DB/run_list) ; do
   # fully qualified URI
   FQ_URI="${FQ_BASE}${BUILD_DIR}/${SRC_NAME}.html"
   FQ_URI=$(echo $FQ_URI | sed -e s#build##)
+  #echo "  FQ: ${FQ_URI}"
 
   # extract metadata from content files
   ITEM_TITLE=$(grep '<!-- title:' $ITEM | sed -e 's/^.*: //' | sed -e 's/ -->$//')
@@ -71,32 +71,31 @@ for ITEM in $(cat $DB/run_list) ; do
 
   # for now, all entries must have a title
   if [[ -z $ITEM_TITLE ]] ; then
-    echo "- ignoring $ITEM, no title"
+    echo "ignoring $ITEM, no title"
     continue
   fi
 
   # setup the build directory
   if [ ! -d $BUILD_DIR ] ; then
-    mkdir -pv $BUILD_DIR || $(echo "  * Could not create build dir." ; exit 1)
+    mkdir -pv $BUILD_DIR || $(echo "Could not create build dir." ; exit 1)
   fi
 
   # only process known file extensions
   if [[ "$SRC_TYPE" == "md" || "$SRC_TYPE" == "html" ]] ; then
-    echo "+ $ITEM"
-    echo "  FQ: ${FQ_URI}"
+    echo "$ITEM"
   else
-    echo "- ignoring: unknown type ($SRC_TYPE)"
+    echo "ignoring: unknown type ($SRC_TYPE)"
     continue
   fi
 
   # dump some metadata for offline indexing
   echo "$ITEM|$ITEM_TITLE|$ITEM_SUMMARY" >> $DB/index.csv
   if [ ! -z "$ITEM_TAGS" ] ; then
-    echo "  tags $ITEM_TAGS"
+    #echo "  tags $ITEM_TAGS"
     echo "$ITEM|$ITEM_TITLE|$ITEM_TAGS" >> $DB/tags.csv
   fi
   if [ ! -z $ITEM_CATS ] ; then
-    echo "  cats $ITEM_CATS"
+    #echo "  cats $ITEM_CATS"
     echo "$ITEM|$ITEM_TITLE|$ITEM_CATS" >> $DB/cats.csv
   fi
 
@@ -104,7 +103,7 @@ for ITEM in $(cat $DB/run_list) ; do
   # necessary; long term will have to do multiple replacements per file.
 
   # template magic: header
-  sed "s/{{TITLE}}/${ITEM_TITLE}/" themes/${THEME}/HEADER.html | \
+  sed "s/{{TITLE}}/${ITEM_TITLE}/" themes/${THEME}/HEADER_body.html | \
   sed "s/{{HANDLE}}/${HANDLE}/" | \
   sed "s#{{URL}}#${FQ_URI}#" | \
   sed "s/{{SUMMARY}}/${ITEM_SUMMARY}/" | \
@@ -115,17 +114,17 @@ for ITEM in $(cat $DB/run_list) ; do
 
   # convert content body if necessary, otherwise use raw HTML
   if [[ "$SRC_TYPE" == "md" ]] ; then
-    echo "  convert: $ITEM -> $BUILD_DIR/$SRC_NAME.html"
+    #echo "  convert: $ITEM -> $BUILD_DIR/$SRC_NAME.html"
     tools/Markdown_1.0.1/Markdown.pl $ITEM >> $BUILD_DIR/$SRC_NAME.html
   elif [[ "$SRC_TYPE" == "html" ]] ; then
-    echo "  concat : $ITEM -> $BUILD_DIR/$SRC_NAME.html"
+    #echo "  concat : $ITEM -> $BUILD_DIR/$SRC_NAME.html"
     cat $ITEM >> $BUILD_DIR/$SRC_NAME.html
   fi
 
   # template magic: footer
   LAST_MOD=$(echo $ITEM_MOD_DATE | sed -e "s/T.*$//")
   EDIT_URL="${GIT_BASE}${ITEM}"
-  sed "s/{{LAST_MOD}}/${LAST_MOD}/g" themes/${THEME}/FOOTER.html | \
+  sed "s/{{LAST_MOD}}/${LAST_MOD}/g" themes/${THEME}/FOOTER_body.html | \
   sed "s#{{EDIT_URL}}#${EDIT_URL}#g" | \
   sed "s#{{BASE_URL}}#${BASE_URL}#g" >> $BUILD_DIR/$SRC_NAME.html
 
